# Generated by Django 4.2.7 on 2025-12-03 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_student_options_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید با فرمت 09123456789 باشد', regex='^09\\d{9}$')], verbose_name='شماره تلفن'),
        ),
    ]
