# Generated by Django 4.2.7 on 2025-12-03 19:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید با فرمت 09123456789 باشد', regex='^09\\d{9}$')], verbose_name='شماره تلفن دانش\u200cآموز'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='attendance.teacher', verbose_name='معلم مرتبط'),
        ),
    ]
