# Generated by Django 4.2.7 on 2025-12-04 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_student_phone_number_userprofile_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'اولیا', 'verbose_name_plural': 'اولیا'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school_name',
            field=models.CharField(blank=True, help_text='نام مدرسه برای نمایش در سیستم', max_length=200, null=True, verbose_name='نام مدرسه'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='attendance.parent', verbose_name='اولیا/سرپرست'),
        ),
    ]
