# Generated by Django 4.2.7 on 2025-12-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_student_updated_at_student_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('absent', 'غایب'), ('excused', 'غایب موجه'), ('late', 'تأخیر')], default='absent', max_length=10, verbose_name='وضعیت'),
        ),
    ]
