# Generated by Django 4.2.7 on 2025-12-04 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_present_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید با فرمت 09123456789 باشد', regex='^09\\d{9}$')], verbose_name='شماره تلفن'),
        ),
    ]
